### ISSUE TITLE
Sonoma Boot problem

### ISSUE THREAD

**Issue by jhay06** [QuanticalityIsHere/lenovo-t430-efi#1]
When booting up sonoma with Wifi card enabled , it gets stuck. 
when i disable it from the small switch at the right side of the laptop beside the sd card reader, it boots..

**Comment by QuanticalityIsHere** [comment]
@jhay06 do you have a spare PC?

**Comment by QuanticalityIsHere** [comment]
> When booting up sonoma with Wifi card enabled , it gets stuck. when i disable it from the small switch at the right side of the laptop beside the sd card reader, it boots..

@jhay06 reply fast yk,

**Comment by jhay06** [comment]
> @jhay06 do you have a spare PC?

none but i have spare hdd . old hdd

**Comment by QuanticalityIsHere** [comment]
@jhay06 that is fine then. I am outside right now. I will be back in an hour.

**Comment by QuanticalityIsHere** [comment]
@jhay06 , while i am outside, can you please install sonoma with the wifi turned off on that external hard drive?

**Comment by jhay06** [comment]
im sorry , cant do it right now maybe tomorrow will try then will send result here .

**Comment by QuanticalityIsHere** [comment]
Ok

**Comment by QuanticalityIsHere** [comment]
@jhay06, I won't be there tommorow, as I have a dental appointment. So, I will try to tell you all that you have to do tommorow.

1. Disable that switch which I told you and install macOS Sonoma by connecting an **Ethernet Cable** and then install it ON A SEPERATE PARTITION OF THE DISK YOU ARE USING. IF YOU ARE USING AN EXTERNAL DISK, IT **WILL NOT WORK**.

2. After installation of macOS Sonoma, download this app called HeliPort from [here](https://github.com/OpenIntelWireless/HeliPort/releases).

3. Install HeliPort and restart your laptop. Before the ThinkPad logo appears, enable that switch which I told you back on.

4. If it still doesn't work, you might need to use a USB WiFi adapter, or you can delete Sonoma by rebooting into Ventura.

5. Happy Hackintoshing!

**Comment by QuanticalityIsHere** [comment]
@jhay06, please tell me what happened.

**Comment by QuanticalityIsHere** [comment]
@jhay06 , what happened?

**Comment by QuanticalityIsHere** [comment]
@jhay06 , if you wont respond, im afraid i will have to close this issue

**Comment by jhay06** [comment]
im sorry i cant today i have an urgent matters to do in my work will try tomorrow thank you

**Comment by jhay06** [comment]
will close for now , will send update once i got some time again thank you

**Comment by QuanticalityIsHere** [comment]
Alright.
